[package]
name = "ellipse_tangent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
chromosome = "0.1.0"
rand = "0.8.5"
