[package]
name = "ellipse_tangent_simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"
chromosome = "0.1.0"
ellipse_tangent = { path = "../.."}
rand = "0.8.5"
