name: Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  EMULATOR_IMAGE: system-images;android-23;google_apis;armeabi-v7a
  BUILD_TOOLS_VERSION: 23.0.3
  emulator_name: 2.7_QVGA_API_23

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install SDK packages
      run: sdkmanager "platform-tools" "build-tools;$BUILD_TOOLS_VERSION" "emulator" "$EMULATOR_IMAGE"

    - name: Setup target
      run: rustup target add armv7-linux-androideabi

    - name: Build
      run: PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin cargo build --verbose --target armv7-linux-androideabi

    - name: Create AVD
      run: |
        echo no | avdmanager create avd --force --name $emulator_name --abi armeabi-v7a --package $EMULATOR_IMAGE
        mkdir -p ~/.android/avd/$emulator_name.avd/ && cp ./android/avd/$emulator_name.avd/config.ini ~/.android/avd/$emulator_name.avd/config.ini
        echo "avd.ini.encoding=UTF-8
        path=$HOME/.android/avd/$emulator_name.avd
        path.rel=avd/$emulator_name.avd
        target=android-23" >> $HOME/.android/avd/$emulator_name.ini

    - name: Install pulse library
      run: sudo apt install -y libpulse0

    - name: Run emulator
      run: $ANDROID_HOME/emulator/emulator -avd $emulator_name -no-window -no-audio -netdelay none -netspeed full &

    - name: Wait for emulator
      run: adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'

    - name: Run tests
      run: PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin cargo test --verbose --target armv7-linux-androideabi
